from .knn import KNN,KNN_Regressor
from .lda import LDA
from .qda import QDA
from .linear_regression import LinearRegression
from .linear_classification import LinearClassification
from .ridge_regression import Ridge
from .ridge_classifier import RidgeClassifier
from .naive_bayes import BernoulliNaiveBayes,GaussianNaiveBayes,MultinomialNaiveBayes
from .perceptron import perceptron
from .decison_tree import DecisionTreeClassifier,DecisionTreeRegressor
from .polynomial import PolynomialRegression,PolynomialClassification