from .knn import KNN,KNN_Regressor
from .lda import LDA
from .qda import QDA
from .ridge_regression import Ridge
from .ridge_classifier import RidgeClassifier
from .naive_bayes import BernoulliNaiveBayes,GaussianNaiveBayes,MultinomialNaiveBayes
from .perceptron import perceptron
from .decison_tree import DecisionTreeClassifier,DecisionTreeRegressor
from .leastsquares import PolynomialRegression,PolynomialClassification,LinearClassification,LinearRegression