from .knn import KNN,KNN_Regressor
from .discriminantanalysis import LDA,QDA
from .naive_bayes import BernoulliNaiveBayes,GaussianNaiveBayes,MultinomialNaiveBayes
from .perceptron import Perceptron
from .decison_tree import DecisionTreeClassifier,DecisionTreeRegressor
from .leastsquares import PolynomialRegression,PolynomialClassification,LinearClassification,LinearRegression
from .leastsquares_regularised import RidgeClassifier,RidgeRegressor,LassoClassifier,LassoRegressor